In [4]:
import pandas as pd

In [5]:
df = pd.read_json("../data/India-Food-Delivery-Time-Prediction.txt")

In [6]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:33:33,11:45:29,conditions Sunny,High,2,Snack,motorcycle,0.0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:37,19:51:49,conditions Stormy,Jam,2,Snack,scooter,1.0,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,8:32:58,8:48:47,conditions Sandstorms,Low,0,Drinks,motorcycle,1.0,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:03:58,18:12:52,conditions Sunny,Medium,0,Buffet,motorcycle,1.0,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:34:16,13:45:36,conditions Cloudy,High,1,Snack,scooter,1.0,No,Metropolitian,(min) 30

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41953 entries, 0 to 41952
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           41953 non-null  str
 1   Delivery_person_ID           41953 non-null  str
 2   Delivery_person_Age          40234 non-null  float64
 3   Delivery_person_Ratings      40190 non-null  float64
 4   Restaurant_latitude          41953 non-null  float64
 5   Restaurant_longitude         41953 non-null  float64
 6   Delivery_location_latitude   41953 non-null  float64
 7   Delivery_location_longitude  41953 non-null  float64
 8   Order_Date                   41953 non-null  str
 9   Time_Orderd                  40353 non-null  str
 10  Time_Order_picked            41953 non-null  str
 11  Weatherconditions            41953 non-null  str
 12  Road_traffic_density         41953 non-null  str
 13  Vehicle_condition            41953 non-null  int64
 14  Type_of_order                41953 non-null  str
 15  Type_of_vehicle              41953 non-null  str
 16  multiple_deliveries          41048 non-null  float64
 17  Festival                     41953 non-null  str
 18  City                         41953 non-null  str
 19  Time_taken(min)              41953 non-null  str
dtypes: float64(7), int64(1), str(12)
memory usage: 6.4 MB

In [8]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1719
Delivery_person_Ratings        1763
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1600
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             905
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [9]:
df["Weatherconditions"].unique()

<StringArray>
[     'conditions Sunny',     'conditions Stormy', 'conditions Sandstorms',
     'conditions Cloudy',        'conditions Fog',      'conditions Windy',
        'conditions NaN']
Length: 7, dtype: str

In [10]:
df["Road_traffic_density"].unique()

<StringArray>
['High ', 'Jam ', 'Low ', 'Medium ', 'NaN ']
Length: 5, dtype: str

In [11]:
df["Time_taken(min)"].head()

0    (min) 24
1    (min) 33
2    (min) 26
3    (min) 21
4    (min) 30
Name: Time_taken(min), dtype: str

In [12]:
df.shape

(41953, 20)

In [13]:
df["Weatherconditions"] = df["Weatherconditions"].str.replace("conditions", "")

In [14]:
df["Weatherconditions"].unique()

<StringArray>
[' Sunny', ' Stormy', ' Sandstorms', ' Cloudy', ' Fog', ' Windy', ' NaN']
Length: 7, dtype: str

In [15]:
df["Weatherconditions"] = df["Weatherconditions"].str.strip()

In [16]:
df["Weatherconditions"].unique()

<StringArray>
['Sunny', 'Stormy', 'Sandstorms', 'Cloudy', 'Fog', 'Windy', 'NaN']
Length: 7, dtype: str

In [17]:
df["Road_traffic_density"] = df["Road_traffic_density"].str.strip()

In [18]:
df["Road_traffic_density"].unique()

<StringArray>
['High', 'Jam', 'Low', 'Medium', 'NaN']
Length: 5, dtype: str

In [19]:
df["Time_taken(min)"] = df["Time_taken(min)"].str.replace("(min) ", "")
df["Time_taken(min)"] = df["Time_taken(min)"].astype(int)
df["Time_taken(min)"].unique()

array([24, 33, 26, 21, 30, 40, 32, 34, 46, 23, 20, 41, 15, 36, 39, 18, 38,
       47, 12, 22, 25, 10, 19, 11, 28, 52, 16, 27, 17, 14, 37, 44, 42, 31,
       13, 29, 49, 35, 50, 48, 43, 54, 53, 45, 51])

In [20]:
df["Time_taken(min)"].dtype

dtype('int64')

In [21]:
df.to_csv("../data/cleaned_delivery_data.csv", index=False)

In [22]:
df = pd.read_csv("../data/cleaned_delivery_data.csv")

In [23]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:33:33,11:45:29,Sunny,High,2,Snack,motorcycle,0.0,No,Urban,24
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:37,19:51:49,Stormy,Jam,2,Snack,scooter,1.0,No,Metropolitian,33
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,8:32:58,8:48:47,Sandstorms,Low,0,Drinks,motorcycle,1.0,No,Urban,26
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:03:58,18:12:52,Sunny,Medium,0,Buffet,motorcycle,1.0,No,Metropolitian,21
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:34:16,13:45:36,Cloudy,High,1,Snack,scooter,1.0,No,Metropolitian,30

In [24]:
df.replace("NaN",pd.NA,inplace=True)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:33:33,11:45:29,Sunny,High,2,Snack,motorcycle,0.0,No,Urban,24
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:37,19:51:49,Stormy,Jam,2,Snack,scooter,1.0,No,Metropolitian,33
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,8:32:58,8:48:47,Sandstorms,Low,0,Drinks,motorcycle,1.0,No,Urban,26
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:03:58,18:12:52,Sunny,Medium,0,Buffet,motorcycle,1.0,No,Metropolitian,21
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:34:16,13:45:36,Cloudy,High,1,Snack,scooter,1.0,No,Metropolitian,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41948,0x1178,RANCHIRES16DEL01,35.0,4.2,23.371292,85.327872,23.481292,85.437872,08-03-2022,21:47:47,21:59:27,Windy,Jam,2,Drinks,motorcycle,1.0,No,Metropolitian,33
41949,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:36:22,11:48:07,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
41950,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:56,0:08:55,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
41951,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:40:13,13:42:00,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
41952,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:12:55,17:19:35,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [25]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1719
Delivery_person_Ratings        1763
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1600
Time_Order_picked                 0
Weatherconditions               569
Road_traffic_density            555
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             905
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [26]:
df.dtypes

ID                                 str
Delivery_person_ID                 str
Delivery_person_Age            float64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                         str
Time_Orderd                        str
Time_Order_picked                  str
Weatherconditions                  str
Road_traffic_density               str
Vehicle_condition                int64
Type_of_order                      str
Type_of_vehicle                    str
multiple_deliveries            float64
Festival                           str
City                               str
Time_taken(min)                  int64
dtype: object

In [27]:
df["Delivery_person_Age"] = df["Delivery_person_Age"].fillna(df["Delivery_person_Age"].median())
df["Delivery_person_Ratings"] = df["Delivery_person_Ratings"].fillna(df["Delivery_person_Ratings"].median())
df["multiple_deliveries"] = df["multiple_deliveries"].fillna(df["multiple_deliveries"].median())

In [28]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1600
Time_Order_picked                 0
Weatherconditions               569
Road_traffic_density            555
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [29]:
df["Weatherconditions"] = df["Weatherconditions"].fillna(df["Weatherconditions"].mode()[0])
df["Road_traffic_density"] = df["Road_traffic_density"].fillna(df["Road_traffic_density"].mode()[0])

In [30]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1600
Time_Order_picked                 0
Weatherconditions                 0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken(min)                   0
dtype: int64

In [31]:
df = df.dropna(subset=["Time_Orderd"])

In [32]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [33]:
df.to_csv("../data/cleaned_delivery_data.csv", index=False)

In [34]:
import pandas as pd
df = pd.read_csv("../data/cleaned_delivery_data.csv")

In [35]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], format="%d-%m-%Y")

In [36]:
df["Order_Date"].head()

0   2022-03-19
1   2022-03-25
2   2022-03-19
3   2022-04-05
4   2022-03-26
Name: Order_Date, dtype: datetime64[us]

In [37]:
df["day_of_week"] = df["Order_Date"].dt.day_name()

In [38]:
df[["Order_Date", "day_of_week"]].head()

  Order_Date day_of_week
0 2022-03-19    Saturday
1 2022-03-25      Friday
2 2022-03-19    Saturday
3 2022-04-05     Tuesday
4 2022-03-26    Saturday

In [39]:
df["is_weekend"] = df["day_of_week"].isin(["Saturday", "Sunday"])

In [40]:
df[["day_of_week", "is_weekend"]].head()

  day_of_week  is_weekend
0    Saturday        True
1      Friday       False
2    Saturday        True
3     Tuesday       False
4    Saturday        True

In [41]:
df[["Time_Orderd", "Time_Order_picked"]].head()

  Time_Orderd Time_Order_picked
0    11:33:33          11:45:29
1    19:45:37          19:51:49
2     8:32:58           8:48:47
3    18:03:58          18:12:52
4    13:34:16          13:45:36

In [42]:
df["Time_Orderd"] = pd.to_datetime(df["Time_Orderd"], format="%H:%M:%S")
df["Time_Order_picked"] = pd.to_datetime(df["Time_Order_picked"], format="%H:%M:%S")

In [43]:
df.dtypes

ID                                        str
Delivery_person_ID                        str
Delivery_person_Age                   float64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[us]
Time_Orderd                    datetime64[us]
Time_Order_picked              datetime64[us]
Weatherconditions                         str
Road_traffic_density                      str
Vehicle_condition                       int64
Type_of_order                             str
Type_of_vehicle                           str
multiple_deliveries                   float64
Festival                                  str
City                                      str
Time_taken(min)                         int64
day_of_week                               str
is_weekend                               bool
dtype: object

In [44]:
df["preparation_time"] = (
    df["Time_Order_picked"] - df["Time_Orderd"]
).dt.total_seconds() / 60

In [45]:
df["preparation_time"].head()

0    11.933333
1     6.200000
2    15.816667
3     8.900000
4    11.333333
Name: preparation_time, dtype: float64

In [46]:
df["order_hour"] = df["Time_Orderd"].dt.hour

In [47]:
df["order_hour"].head()

0    11
1    19
2     8
3    18
4    13
Name: order_hour, dtype: int32

In [48]:
df = df.drop(columns=["ID", "Delivery_person_ID"])

In [49]:
df.columns

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)',
       'day_of_week', 'is_weekend', 'preparation_time', 'order_hour'],
      dtype='str')

In [50]:
df.corr(numeric_only=True)["Time_taken(min)"]

Delivery_person_Age            0.302415
Delivery_person_Ratings       -0.361422
Restaurant_latitude            0.012341
Restaurant_longitude           0.009132
Delivery_location_latitude     0.014493
Delivery_location_longitude    0.012501
Vehicle_condition             -0.242753
multiple_deliveries            0.378697
Time_taken(min)                1.000000
is_weekend                    -0.006945
preparation_time               0.056672
order_hour                     0.186558
Name: Time_taken(min), dtype: float64

In [51]:
df.to_csv("../data/cleaned_delivery_data.csv", index=False)

In [52]:
X = df.drop(columns=["Time_taken(min)"])
y = df["Time_taken(min)"]

In [53]:
X.shape, y.shape

((40353, 21), (40353,))

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [56]:
X_train.shape, X_test.shape

((32282, 21), (8071, 21))

In [57]:
X_train.dtypes

Delivery_person_Age                   float64
Delivery_person_Ratings               float64
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[us]
Time_Orderd                    datetime64[us]
Time_Order_picked              datetime64[us]
Weatherconditions                         str
Road_traffic_density                      str
Vehicle_condition                       int64
Type_of_order                             str
Type_of_vehicle                           str
multiple_deliveries                   float64
Festival                                  str
City                                      str
day_of_week                               str
is_weekend                               bool
preparation_time                      float64
order_hour                              int32
dtype: object

In [58]:
X_train = X_train.drop(columns=["Order_Date", "Time_Orderd", "Time_Order_picked"])

X_test = X_test.drop(columns=["Order_Date", "Time_Orderd", "Time_Order_picked"])

In [59]:
X_train.dtypes

Delivery_person_Age            float64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Weatherconditions                  str
Road_traffic_density               str
Vehicle_condition                int64
Type_of_order                      str
Type_of_vehicle                    str
multiple_deliveries            float64
Festival                           str
City                               str
day_of_week                        str
is_weekend                        bool
preparation_time               float64
order_hour                       int32
dtype: object

In [60]:
X_train = pd.get_dummies(X_train, drop_first=True)

X_test = pd.get_dummies(X_test, drop_first=True)

In [61]:
X_train.shape

(32282, 35)

In [62]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [63]:
y_pred = model.predict(X_test)

In [64]:
y_pred[:5]

array([20.6860475 , 24.6609711 , 22.79096791, 47.84186994, 23.22346695])

In [65]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison.head()

   Actual  Predicted
0      17  20.686048
1      31  24.660971
2      24  22.790968
3      48  47.841870
4      28  23.223467

In [66]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = mse ** 0.5

r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 4.695663543674381
MSE: 34.799862568355394
RMSE: 5.899140833066744
R2 Score: 0.6044735603046629

In [67]:
from sklearn.ensemble import RandomForestRegressor

In [68]:
rf_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

In [69]:
rf_model.fit(X_train, y_train)

KeyboardInterrupt:

In [70]:
rf_pred = rf_model.predict(X_test)

IndexError: list index out of range

In [ ]:
rf_mae = mean_absolute_error(y_test, rf_pred)

rf_mse = mean_squared_error(y_test, rf_pred)

rf_rmse = rf_mse ** 0.5

rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest MAE:", rf_mae)
print("Random Forest MSE:", rf_mse)
print("Random Forest RMSE:", rf_rmse)
print("Random Forest R2:", rf_r2)

In [71]:
from xgboost import XGBRegressor

In [ ]:
xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

In [ ]:
xgb_model.fit(X_train, y_train)

In [ ]:
xgb_pred = xgb_model.predict(X_test)

In [ ]:
xgb_mae = mean_absolute_error(y_test, xgb_pred)

xgb_mse = mean_squared_error(y_test, xgb_pred)

xgb_rmse = xgb_mse ** 0.5

xgb_r2 = r2_score(y_test, xgb_pred)

print("XGBoost MAE:", xgb_mae)
print("XGBoost MSE:", xgb_mse)
print("XGBoost RMSE:", xgb_rmse)
print("XGBoost R2:", xgb_r2)

In [72]:
from sklearn.model_selection import GridSearchCV

In [73]:
param_grid = {
    "n_estimators": [200, 500,600,700,900,1000],
    "max_depth": [6, 8, 10],
    "learning_rate": [0.03, 0.05, 0.1],
    "subsample": [0.8, 1.0]
}

In [ ]:
grid_search = GridSearchCV(
    estimator=XGBRegressor(random_state=42),
    param_grid=param_grid,
    cv=3,
    scoring="r2",
    verbose=1,
    n_jobs=-1
)

In [ ]:
grid_search.fit(X_train, y_train)

In [ ]:
print(grid_search.best_params_)
print(grid_search.best_score_)

In [ ]:
xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.1,
    max_depth=8,
    random_state=42,
    tree_method="hist",
    device="cuda"
)

In [ ]:
xgb_model.fit(X_train, y_train)

In [74]:
from geopy.distance import geodesic

In [75]:
df["distance_km"] = df.apply(
    lambda row: geodesic(
        (
            row["Restaurant_latitude"],
            row["Restaurant_longitude"]
        ),
        (
            row["Delivery_location_latitude"],
            row["Delivery_location_longitude"]
        )
    ).km,
    axis=1
)

In [76]:
df["distance_km"].head()

0     3.020737
1    20.143737
2     1.549693
3     7.774497
4     6.197898
Name: distance_km, dtype: float64

In [99]:
X = df.drop(columns=["Time_taken(min)"])

y = df["Time_taken(min)"]

In [100]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [101]:
X_train = X_train.drop(
    columns=["Order_Date", "Time_Orderd", "Time_Order_picked"]
)

X_test = X_test.drop(
    columns=["Order_Date", "Time_Orderd", "Time_Order_picked"]
)

In [102]:
X_train = pd.get_dummies(X_train, drop_first=True)

X_test = pd.get_dummies(X_test, drop_first=True)

In [103]:
X_train, X_test = X_train.align(
    X_test,
    join="left",
    axis=1,
    fill_value=0
)

In [107]:
xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.1,
    max_depth=8,
    random_state=42,
    tree_method="hist",
    device="cuda"
)

xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [108]:
xgb_pred = xgb_model.predict(X_test)

xgb_r2 = r2_score(y_test, xgb_pred)

print(xgb_r2)

0.8308162689208984

In [109]:
from catboost import CatBoostRegressor

In [110]:
X = df.drop(columns=["Time_taken(min)"])

y = df["Time_taken(min)"]

In [111]:
X = X.drop(
    columns=["Order_Date", "Time_Orderd", "Time_Order_picked"]
)

In [112]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [113]:
cat_features = X_train.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print(cat_features)

['Weatherconditions', 'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle', 'Festival', 'City', 'day_of_week', 'meal_time']

C:\Users\nithi\AppData\Local\Temp\ipykernel_4272\3794235136.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = X_train.select_dtypes(

In [122]:
cat_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    eval_metric="R2",
    verbose=100
)

In [123]:
cat_model.fit(
    X_train,
    y_train,
    cat_features=cat_features
)

0:	learn: 0.0729581	total: 46.7ms	remaining: 46.7s
100:	learn: 0.8366345	total: 5.99s	remaining: 53.4s
200:	learn: 0.8432225	total: 12.2s	remaining: 48.7s
300:	learn: 0.8478452	total: 19.2s	remaining: 44.6s
400:	learn: 0.8523235	total: 26.5s	remaining: 39.5s
500:	learn: 0.8563137	total: 33.7s	remaining: 33.5s
600:	learn: 0.8602299	total: 40.5s	remaining: 26.9s
700:	learn: 0.8639195	total: 46.8s	remaining: 20s
800:	learn: 0.8674157	total: 53.5s	remaining: 13.3s
900:	learn: 0.8708481	total: 1m	remaining: 6.59s
999:	learn: 0.8741986	total: 1m 5s	remaining: 0us

CatBoostRegressor(depth=8, eval_metric='R2', iterations=1000, learning_rate=0.05, loss_function='RMSE', verbose=100)

In [124]:
cat_pred = cat_model.predict(X_test)

cat_r2 = r2_score(y_test, cat_pred)

print(cat_r2)

0.8476068576507323

In [125]:
from lightgbm import LGBMRegressor

In [126]:
lgb_model = LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=8,
    random_state=42
)

In [127]:
print(X_train.dtypes.head())

Delivery_person_Age           float64
Delivery_person_Ratings       float64
Restaurant_latitude           float64
Restaurant_longitude          float64
Delivery_location_latitude    float64
dtype: object

In [128]:
X_train.select_dtypes(include=["object"]).columns

C:\Users\nithi\AppData\Local\Temp\ipykernel_4272\165498385.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X_train.select_dtypes(include=["object"]).columns

Index(['Weatherconditions', 'Road_traffic_density', 'Type_of_order',
       'Type_of_vehicle', 'Festival', 'City', 'day_of_week', 'meal_time'],
      dtype='str')

In [129]:
X_train_encoded = pd.get_dummies(
    X_train,
    drop_first=True
)

X_test_encoded = pd.get_dummies(
    X_test,
    drop_first=True
)

In [130]:
X_train_encoded, X_test_encoded = X_train_encoded.align(
    X_test_encoded,
    join="left",
    axis=1,
    fill_value=0
)

In [131]:
lgb_model = LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=8,
    random_state=42
)

In [132]:
lgb_model.fit(
    X_train_encoded,
    y_train
)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001250 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1668
[LightGBM] [Info] Number of data points in the train set: 32282, number of used features: 42
[LightGBM] [Info] Start training from score 26.323214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMRegressor(learning_rate=0.05, max_depth=8, n_estimators=1000,
              random_state=42)

In [133]:
lgb_pred = lgb_model.predict(X_test_encoded)

lgb_r2 = r2_score(y_test, lgb_pred)

print(lgb_r2)

0.8354853067764634

In [134]:
cat_model.save_model(
    "../models/catboost_model.cbm"
)

In [135]:
xgb_model.save_model(
    "../models/xgboost_model.json"
)

In [136]:
import joblib

In [137]:
joblib.dump(
    rf_model,
    "../models/random_forest_model.pkl"
)

['../models/random_forest_model.pkl']

In [138]:
final_df = df.copy()

In [139]:
final_df = final_df.drop(
    columns=[
        "weather_score",
        "traffic_score",
        "is_rush_hour"
    ],
    errors="ignore"
)

In [140]:
final_df.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,...,multiple_deliveries,Festival,City,Time_taken(min),day_of_week,is_weekend,preparation_time,order_hour,distance_km,meal_time
0,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,1900-01-01 11:33:33,1900-01-01 11:45:29,Sunny,...,0.0,No,Urban,24,Saturday,True,11.933333,11,3.020737,Lunch
1,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,1900-01-01 19:45:37,1900-01-01 19:51:49,Stormy,...,1.0,No,Metropolitian,33,Friday,False,6.200000,19,20.143737,Dinner
2,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,1900-01-01 08:32:58,1900-01-01 08:48:47,Sandstorms,...,1.0,No,Urban,26,Saturday,True,15.816667,8,1.549693,Breakfast
3,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,1900-01-01 18:03:58,1900-01-01 18:12:52,Sunny,...,1.0,No,Metropolitian,21,Tuesday,False,8.900000,18,7.774497,Dinner
4,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,1900-01-01 13:34:16,1900-01-01 13:45:36,Cloudy,...,1.0,No,Metropolitian,30,Saturday,True,11.333333,13,6.197898,Lunch

In [141]:
final_df.columns

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)',
       'day_of_week', 'is_weekend', 'preparation_time', 'order_hour',
       'distance_km', 'meal_time'],
      dtype='str')

In [142]:
X = final_df.drop(columns=["Time_taken(min)"])

y = final_df["Time_taken(min)"]

In [143]:
X = X.drop(
    columns=[
        "Order_Date",
        "Time_Orderd",
        "Time_Order_picked"
    ]
)

In [144]:
X.columns

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Weatherconditions',
       'Road_traffic_density', 'Vehicle_condition', 'Type_of_order',
       'Type_of_vehicle', 'multiple_deliveries', 'Festival', 'City',
       'day_of_week', 'is_weekend', 'preparation_time', 'order_hour',
       'distance_km', 'meal_time'],
      dtype='str')

In [145]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [146]:
X_train.shape, X_test.shape

((32282, 20), (8071, 20))

In [147]:
cat_features = X_train.select_dtypes(
    include=["object", "string", "category"]
).columns.tolist()

print(cat_features)

['Weatherconditions', 'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle', 'Festival', 'City', 'day_of_week', 'meal_time']

In [148]:
X_train_encoded = pd.get_dummies(
    X_train,
    drop_first=True
)

X_test_encoded = pd.get_dummies(
    X_test,
    drop_first=True
)

In [149]:
X_train_encoded, X_test_encoded = X_train_encoded.align(
    X_test_encoded,
    join="left",
    axis=1,
    fill_value=0
)

In [150]:
X_train_encoded.shape

(32282, 39)

In [151]:
from sklearn.ensemble import RandomForestRegressor

In [157]:
rf_model = RandomForestRegressor(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

In [158]:
rf_model.fit(
    X_train_encoded,
    y_train
)

RandomForestRegressor(n_estimators=500, n_jobs=-1, random_state=42)

In [159]:
rf_pred = rf_model.predict(
    X_test_encoded
)

In [160]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [161]:
rf_r2 = r2_score(y_test, rf_pred)

print(rf_r2)

0.8287952139941241

In [162]:
import joblib

In [163]:
joblib.dump(
    rf_model,
    "../models/random_forest_model.pkl"
)

['../models/random_forest_model.pkl']

In [164]:
from xgboost import XGBRegressor

In [165]:
xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.1,
    max_depth=8,
    random_state=42,
    tree_method="hist",
    device="cuda"
)

In [166]:
xgb_model.fit(
    X_train_encoded,
    y_train
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [167]:
xgb_pred = xgb_model.predict(
    X_test_encoded
)

In [168]:
xgb_r2 = r2_score(
    y_test,
    xgb_pred
)

print(xgb_r2)

0.8256081938743591

In [169]:
xgb_model.save_model(
    "../models/xgboost_model.json"
)

In [170]:
from catboost import CatBoostRegressor

In [171]:
cat_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    eval_metric="R2",
    random_seed=42,
    verbose=100
)

In [172]:
cat_model.fit(
    X_train,
    y_train,
    cat_features=cat_features
)

0:	learn: 0.0693585	total: 74.1ms	remaining: 1m 14s
100:	learn: 0.8360590	total: 6.11s	remaining: 54.4s
200:	learn: 0.8423588	total: 12s	remaining: 47.8s
300:	learn: 0.8467383	total: 18.6s	remaining: 43.2s
400:	learn: 0.8509184	total: 25.2s	remaining: 37.6s
500:	learn: 0.8553450	total: 31.6s	remaining: 31.4s
600:	learn: 0.8592801	total: 36.6s	remaining: 24.3s
700:	learn: 0.8629925	total: 41.7s	remaining: 17.8s
800:	learn: 0.8665964	total: 46.8s	remaining: 11.6s
900:	learn: 0.8696497	total: 51.9s	remaining: 5.7s
999:	learn: 0.8727460	total: 57s	remaining: 0us

CatBoostRegressor(depth=8, eval_metric='R2', iterations=1000, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=100)

In [173]:
cat_pred = cat_model.predict(
    X_test
)

In [174]:
cat_r2 = r2_score(
    y_test,
    cat_pred
)

print(cat_r2)

0.8473780556232806

In [175]:
cat_model.save_model(
    "../models/catboost_model.cbm"
)

In [176]:

sample_data = {
    "Delivery_person_Age": 29,
    "Delivery_person_Ratings": 4.7,

    "Restaurant_latitude": 12.9716,
    "Restaurant_longitude": 77.5946,

    "Delivery_location_latitude": 12.9352,
    "Delivery_location_longitude": 77.6245,

    "Weatherconditions": "Sunny",
    "Road_traffic_density": "High",

    "Vehicle_condition": 2,
    "Type_of_order": "Snack",
    "Type_of_vehicle": "Bike",

    "multiple_deliveries": 1,
    "Festival": "No",
    "City": "Urban",

    "Order_Date": "2024-05-26",
    "Time_Orderd": "18:45"
}

In [187]:
import pandas as pd

sample_df = pd.DataFrame([sample_data])

In [191]:
from src.predict import predict_eta

In [192]:
prediction = predict_eta(sample_df)

print(prediction)

TypeError: must be real number, not Series

In [193]:
from importlib import reload
import src.preprocessing

reload(src.preprocessing)

In [194]:
import src.predict

reload(src.predict)

In [196]:
from src.predict import predict_eta

In [197]:
prediction = predict_eta(sample_df)

print(prediction)

ValueError: invalid literal for int() with base 10: '0    18'

In [206]:
from importlib import reload
import src.preprocessing
import src.predict

reload(src.preprocessing)
reload(src.predict)

In [207]:
from src.predict import predict_eta

prediction = predict_eta(sample_df)

print(prediction)

ValueError: Provide either 'preparation_time' or 'Time_Order_picked' so preparation_time can be computed.